In [3]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
inds=np.where(a[:,-1]>=9)[0]#it must be 0
inds

array([2])

In [6]:
b=np.random.random((2,3))#注意这里是两个括号
b

array([[ 0.68630343,  0.0035017 ,  0.75096523],
       [ 0.60275242,  0.2999518 ,  0.06357952]])

In [7]:
l=[1,2,3,4,5]
l[2]=8
l

[1, 2, 8, 4, 5]

In [8]:
del l[2] #删除8
l

[1, 2, 4, 5]

In [12]:
l[:-1]#从倒数第二个取到第一个

[1, 2, 4]

In [18]:
l.insert(2,5)

In [19]:
l.pop()

5

In [15]:
t=tuple(l)
t

(1, 2, 4, 5)

In [17]:
t+=(7,)#创建一个空的列表并且相加

In [20]:
#元祖不能修改其中的值，但是能够用del删除整个元祖，被删除之后整个元祖就不能被访问
# +号对于列表和元祖的意义在于连接，并不是相加,*号在于复制，并不是相乘的意思
#任意无符号的对象，以逗号隔开，默认为元组
#字典的每个键值(key=>value)对用冒号(:)分割，每个对之间用逗号(,)分割，整个字典包括在花括号({})中 ,格式如下所示： 

In [22]:
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
dict['Age']=8 #修改默认覆盖

In [23]:
dict['Age']

8

In [24]:
dict['School'] = "DPS School" #新增一个新的键值对
del dict['Name']; # 删除键是'Name'的条目
dict.clear();     # 清空词典所有条目
del dict ;        # 删除词典

In [30]:
#不允许同一个键出现两次。创建时如果同一个键被赋值两次，后一个值会被记住，如下实例：
#键必须不可变，所以可以用数字，字符串或元组充当，所以用列表就不行，如下实例：
dict={'zzq':20,'ysh':'21'}
print 'the length of the dictionary:' ,len(dict)
print 'the value of the zzq:' ,dict.get('zzq')
dict.items()#以迭代的方式返回这个字典
dict.values()

the length of the dictionary: 2
the value of the zzq: 20


['21', 20]

In [31]:
p=np.arange(12).reshape(3,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
p.sum(axis=0)#0是列

array([12, 15, 18, 21])

In [33]:
p.sum(axis=1)#1是列

array([ 6, 22, 38])

In [35]:
e=np.arange(3)
e**3#操作符是对数组中的每个元素逐一进行的

array([0, 1, 8])

In [36]:
e=np.arange(12)

In [38]:
 e[: :-1 ]  #反转a 但是不改变原数组列表的值

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [40]:
e.reshape(3,4)
#e[2,3]不能访问，因为它的实际形状还是一个一维的数据


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
d=np.arange(16).reshape(4,4)

In [48]:
d[2,3]

11

In [49]:
d[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
#当少于提供的索引数目少于轴数时，已给出的数值按秩的顺序复制，确失的索引则默认为是整个切片：
d[-1]

array([12, 13, 14, 15])

In [51]:
#多维数组的遍历是以是第一个轴为基础的：
#flat是numpy的一个迭代器
for elem in d.flat:
    print elem

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [52]:
d.ravel()#平坦化数组

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:

d.shape=(2,8)
d.transpose()


array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [61]:
#O列1行
zero=np.zeros((3,4))

In [70]:
ones=np.ones((3,4))
heng=np.hstack((zero,ones))
heng
heng_cat=np.concatenate((zero,ones),axis=1)
heng_cat

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.]])

In [71]:
full2=np.full((2,3),12)


In [72]:
print full2[1,2]

12


In [73]:
deep=np.dstack((zero,ones))

In [74]:
deep#深度组合

array([[[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]]])

In [75]:
print np.linspace(1, 10, num=10)
#给定一个区间，取其 N 等分点组成一个一维数组

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [ ]:
x, y = np.meshgrid(np.arange(-1, 1, 0.01), np.arange(-1, 1, 0.01))
#根据给定的坐标向量创建坐标矩阵。 