In [22]:
import numpy as np
ls1=range(10)
print list(ls1)
type(ls1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [23]:
ls2=np.arange(10)
type(ls2)#数组类型不一样了

numpy.ndarray

In [24]:
import numpy as np
array3=np.array(((1,2,3),(2,3,4)))#注意中间的逗号
#上面使用元组套元组的方式。
array3

array([[1, 2, 3],
       [2, 3, 4]])

In [25]:
array4=np.array([[1,2,3],[2,3,4]])
#上面使用列表套列表的方式

In [4]:
np.ones([3,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [6]:
array3.shape#shape函数返回的是数组是几行几列的元素

(2, 3)

In [7]:
array3.dtype#返回数据类型

dtype('int64')

In [8]:
a=array3.ravel()#将高维数据降为一维数据来处理
a

array([1, 2, 3, 2, 3, 4])

In [9]:
#两者的区别在于ravel方法生成的是原数组的视图，无需占有内存空间，
#但视图的改变会影响到原数组的变化。而flatten方法返回的是真实值，其值的改变并不会影响原数组的更改。
print array3.size
print array3.ndim

6
2


In [11]:
arr4=np.array([[ 1, 2, 3, 4],
[ 5, 6, 7, 8],
[ 9, 10, 11, 12]])
array4

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
np.hstack((array3,array4))#行数必须相同，才能套接

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])

In [15]:
np.vstack((array3,array4)) #列数必须相同才能套接

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
 arr5 = np.array(np.arange(24))

In [17]:
a = arr5.reshape(4,6)#reshape函数可以重新设置数组的行数和列数
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
b = a.tolist()#将a转换成列表
type(b)

list

In [19]:
c=a.astype(float)#将a中的数据类型转换为float


In [21]:
c.dtype

dtype('float64')