In [1]:
import numpy as np

In [3]:
x=np.array([[1,2],[2,3]])
mu_x=np.mean(x,axis=1)
print mu_x

[ 1.5  2.5]


In [4]:
mu_all=np.tile(mu_x,(2,1))#以列为重复2次
print mu_all

[[ 1.5  2.5]
 [ 1.5  2.5]]


In [6]:
print np.diag(mu_all)#求得返回对角线上的值

[ 1.5  2.5]


In [9]:
x1=x-mu_all
print x1
print x1.T
print x1.T*x1
variance=1/2.0*np.diag(x1.T*x1)

[[-0.5 -0.5]
 [ 0.5  0.5]]
[[-0.5  0.5]
 [-0.5  0.5]]
[[ 0.25 -0.25]
 [-0.25  0.25]]


In [8]:
print variance

[ 0.125  0.125]


In [10]:
data_ajust=[]
data_ajust=x-mu_all#直接把data_just从list转化为numpy类型的数据
print data_ajust

[[-0.5 -0.5]
 [ 0.5  0.5]]


In [11]:
print type(data_ajust)

<type 'numpy.ndarray'>


In [12]:
conv=np.cov(x1.T)
print conv

[[ 0.5  0.5]
 [ 0.5  0.5]]


In [13]:
ran=np.random.random(4)#产生四个0到1d的浮点数
print ran

[ 0.72879763  0.95071402  0.17024943  0.63346022]


In [14]:
print np.random.normal(ran,0.3)

[ 0.563405    0.79766638  0.4752634   0.61972884]


In [1]:
#  numpy.random.normal(loc=0.0, scale=1.0, size=None)
# 返回符合高斯分布的数据
# mu是均值
# scale是方差
# size是返回多少个数，默认为1
import numpy as np
data=np.array([[1,1,1],
              [2,2,3]])
print np.nonzero(data==2)

(array([1, 1]), array([0, 1]))


In [2]:
data_2=data[:,1]
print np.nonzero(data_2==2)

(array([1]),)


In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
y=np.array([2,3,4])
print np.sum((x-y)**2)

3


In [3]:
print x*y

[ 2  6 12]


In [4]:
print x.shape[0]

3


In [5]:
from numpy import genfromtxt
my_data = genfromtxt('/home/zzq/Downloads/ex1data1.csv', delimiter=',')
print my_data.shape[0]

97


In [11]:
x=my_data[:,0]
# x=x.reshape(97)
print np.shape(x)
print x

(97,)
[  6.1101   5.5277   8.5186   7.0032   5.8598   8.3829   7.4764   8.5781
   6.4862   5.0546   5.7107  14.164    5.734    8.4084   5.6407   5.3794
   6.3654   5.1301   6.4296   7.0708   6.1891  20.27     5.4901   6.3261
   5.5649  18.945   12.828   10.957   13.176   22.203    5.2524   6.5894
   9.2482   5.8918   8.2111   7.9334   8.0959   5.6063  12.836    6.3534
   5.4069   6.8825  11.708    5.7737   7.8247   7.0931   5.0702   5.8014
  11.7      5.5416   7.5402   5.3077   7.4239   7.6031   6.3328   6.3589
   6.2742   5.6397   9.3102   9.4536   8.8254   5.1793  21.279   14.908
  18.959    7.2182   8.2951  10.236    5.4994  20.341   10.136    7.3345
   6.0062   7.2259   5.0269   6.5479   7.5386   5.0365  10.274    5.1077
   5.7292   5.1884   6.3557   9.7687   6.5159   8.5172   9.1802   6.002
   5.5204   5.0594   5.7077   7.6366   5.8707   5.3054   8.2934  13.394
   5.4369]


In [12]:
print x.mean()

8.1598


In [13]:
print int(30471/100)

304


In [14]:
import tensorflow as tf
c = []
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3])
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2])
    c.append(tf.matmul(a, b))
    sum = tf.add_n(c)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print (sess.run(sum))

InvalidArgumentError: Cannot assign a device to node 'MatMul': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
	 [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](Const, Const_1)]]

Caused by op u'MatMul', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/zzq/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/zzq/.local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/zzq/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/zzq/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/zzq/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/zzq/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/zzq/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/zzq/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/zzq/.local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/zzq/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/zzq/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/zzq/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-a803ff424019>", line 6, in <module>
    c.append(tf.matmul(a, b))
  File "/home/zzq/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1769, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/zzq/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1454, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/home/zzq/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/zzq/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2334, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/zzq/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device to node 'MatMul': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
	 [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](Const, Const_1)]]


In [15]:
import tensorflow as tf